# Use root/example as user/password credentials
version: '3.5'

services:
  neo4j:
    image: neo4j:4.1
    hostname: neo4j
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
      - 5005:5005
    environment:
      - "NEO4J_ACCEPT_LICENSE_AGREEMENT=yes"
      - "NEO4J_AUTH=neo4j/admin"
      - NEO4JLABS_PLUGINS=["apoc"]
    volumes:
      - ./neo4j/plugins:/plugins
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: elastic
    hostname: elastic
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
